//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinoteca.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.VentasProductos = new HashSet<VentasProducto>();
        }
    
        public int IdProducto { get; set; }
        public string Descripcion { get; set; }
        public int IdVariedad { get; set; }
        public int IdTipoProducto { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public string FichaTecnica { get; set; }
        public Nullable<int> IdBodega { get; set; }
        public Nullable<int> Stock { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentasProducto> VentasProductos { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        public virtual Variedad Variedade { get; set; }
    }
}
