//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vinoteca.Datos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variedad()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int IdVariedad { get; set; }
        public string NombreVariedad { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Productos { get; set; }
        public virtual Variedad Variedades1 { get; set; }
        public virtual Variedad Variedade1 { get; set; }
    }
}
